spring:
  datasource:
    username: macbookpro
    password: 19801980
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test




application:
  register-url: http://localhost:8080/api/v1/project-agent
  get-user-update-url: http://localhost:8080/api/v1/agent/updates
  name: project2
  enable-register: false


server:
  port: 8082