spring:
  datasource:
    username: macbookpro
    password: 19801980
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo




application:
  hub-url: http://localhost:8080/api/v1/project-agent
  name: todo